Implement execute for TaskAddCommand
AY2223S1-CS2103T-T13-4/tp pull request #107
Opened 2022-10-04 09:58 UTC by bananamonkey4655

Fixes #102 

- Added TaskList as a field to AddressBook
- Each new task (containing information about Person, description, assignment, isDone) is added to this TaskList object

2022-10-04 11:13 UTC, dexter-sim requested changes

2022-10-04 11:13 UTC, dexter-sim commented on src/main/java/seedu/address/model/AddressBook.java
> +     * Returns the person with the same name as {@code name} if they exist in the address book.
The javadoc for this method should be `task book` instead of `address book`?

2022-10-04 12:03 UTC, bananamonkey4655 commented on src/main/java/seedu/address/model/AddressBook.java
> +     * Returns the person with the same name as {@code name} if they exist in the address book.
Fixed!

2022-10-06 00:19 UTC, dexter-sim approved these changes
lgtm

2022-10-06 00:21 UTC, merged