Add cli syntax for date
AY2223S1-CS2103T-T13-4/tp pull request #138
Opened 2022-10-13 03:36 UTC by dexter-sim

2022-10-14 08:04 UTC, seetohjinwei requested changes
I took a look primarily at the logic bits of the code and found a potential problem!

2022-10-14 08:04 UTC, seetohjinwei commented on src/main/java/taskbook/logic/parser/tasks/TaskDeadlineCommandParser.java
> +        Assignment assignment =
The command `task add m/Bernice Yu o/Bernice Yu d/Description` in the original `TaskAddCommand` throws the wrong error. Perhaps we should check if both `o/` and `m/` flags are provided and throw a different error instead. I took a quick glance at this function and it does not seem to catch that, unless I missed it out!

```
Names should only contain alphanumeric characters and spaces, and it should not be blank
```

We could do something like this
```java
if (argMultimap.getValue(PREFIX_ASSIGN_TO).isPresent()
    && argMultimap.getValue(PREFIX_ASSIGN_FROM).isPresent()) {
    throw new ParseException(ExceptionGoesHere);
}
```

2022-10-14 10:42 UTC, dexter-sim commented on src/main/java/taskbook/logic/parser/tasks/TaskDeadlineCommandParser.java
> +        Assignment assignment =
Good catch.

`task todo m/Bernice Yu o/Bernice Yu d/Description`, as well as the deadline and event variants, will now throw invalid command format message.

2022-10-15 05:11 UTC, bananamonkey4655 approved these changes
LGTM!

2022-10-15 05:39 UTC, xiaobill8 approved these changes
Testcases look good!

2022-10-15 05:45 UTC, seetohjinwei approved these changes

2022-10-15 05:46 UTC, merged