Add tags to tasks
AY2223S1-CS2103T-T13-4/tp pull request #175
Opened 2022-10-23 19:03 UTC by bananamonkey4655

Fixes #23, #168, #4 

- Add tags to `Todo, Deadline, Event` classes
- Allow tags to be saved in `Storage`
- Allow tags to be edited
- Update `UserGuide.md` to include tags

2022-10-24 03:02 UTC, seetohjinwei commented
> ### Issues/bugs:
> * if use `#` prefix for tags, then can't use `#` for address e.g. `contact add n/John a/block 123, #01-01` => error:  tag names should be alphanumeric

Perhaps it would be better if we use `#/TAG` with a `/` instead?

1. It would be more consistent with the other prefixes.
2. It would still allow us to have addresses with unit numbers!

2022-10-25 04:31 UTC, seetohjinwei approved these changes
LGTM!

2022-10-25 06:47 UTC, Nephelite requested changes

2022-10-25 06:47 UTC, Nephelite commented on src/main/java/taskbook/logic/commands/tasks/TaskAddCommand.java
> +        requireAllNonNull(name, description, assignment, tags);
Since tags are not altered in this method, I don't think that a check for null tags is needed here.

2022-10-25 06:47 UTC, Nephelite commented on src/test/java/taskbook/logic/parser/contacts/ContactCategoryParserTest.java
> +        String arguments = " n/John Doe p/98765432 e/johnd@example.com a/John street, block 123";
Since CliSyntax.PREFIX_TAG is #/, I don't think you have to remove the # component from the address.

2022-10-25 06:47 UTC, Nephelite commented on src/test/java/taskbook/testutil/PersonBuilder.java
> +    public static final String DEFAULT_ADDRESS = "123, Jurong West Ave 6";
Since CliSyntax.PREFIX_TAG is #/, I don't think you have to remove the # component from the address.

2022-10-25 06:58 UTC, bananamonkey4655 commented on src/main/java/taskbook/logic/commands/tasks/TaskAddCommand.java
> +        requireAllNonNull(name, description, assignment, tags);
Fixed!

2022-10-25 06:58 UTC, bananamonkey4655 commented on src/test/java/taskbook/logic/parser/contacts/ContactCategoryParserTest.java
> +        String arguments = " n/John Doe p/98765432 e/johnd@example.com a/John street, block 123";
Fixed!

2022-10-25 06:58 UTC, bananamonkey4655 commented on src/test/java/taskbook/testutil/PersonBuilder.java
> +    public static final String DEFAULT_ADDRESS = "123, Jurong West Ave 6";
Fixed!

2022-10-25 06:59 UTC, Nephelite approved these changes

2022-10-25 07:22 UTC, merged