Add static Myself Name
AY2223S1-CS2103T-T13-4/tp pull request #178
Opened 2022-10-24 19:06 UTC by xiaobill8

- Add support for Myself parsing
- Update User Guide

2022-10-25 04:30 UTC, seetohjinwei approved these changes
LGTM!

2022-10-25 07:46 UTC, Nephelite requested changes

2022-10-25 07:46 UTC, Nephelite commented on docs/UserGuide.md
> +**Assigned to** Format:  `task todo o/Name d/DESCRIPTION`
Name probably should be all caps

2022-10-25 07:46 UTC, Nephelite commented on docs/UserGuide.md
> +| **Add Todo: Assigned to**        | `task todo o/Name d/DESCRIPTION` <br> e.g., `task todo o/Sam d/Finish the assignment`
Name should be all caps here too.

2022-10-25 07:46 UTC, Nephelite commented on docs/UserGuide.md
> +| **Add Deadline: Assigned to**    | `task deadline o/Name d/DESCRIPTION t/DATE` <br> e.g., `task deadline o/Sam d/Finish the assignment t/Jan 31 2022`
Here too.

2022-10-25 07:46 UTC, Nephelite commented on docs/UserGuide.md
> +| **Add Event: Assigned to**       | `task event o/Name d/DESCRIPTION t/DATE` <br> e.g., `task event o/Sam d/Finish the assignment t/Jan 31 2022`
Here too.

2022-10-26 08:10 UTC, Nephelite approved these changes

2022-10-26 08:10 UTC, merged