NAME case-sensitivity update
AY2223S1-CS2103T-T13-4/tp pull request #244
Opened 2022-10-31 01:05 UTC by xiaobill8

2022-10-31 01:15 UTC, seetohjinwei requested changes

2022-10-31 01:15 UTC, seetohjinwei commented on docs/UserGuide.md
> +Note: NAME is case-sensitive, as such `John Doe` will be treated as a different
Perhaps this sentence is cut off?

2022-10-31 01:19 UTC, dexter-sim commented on docs/UserGuide.md
> +- in full
@bananamonkey4655 also wrote this full name note somewhere else in the user guide. Perhaps we should decide on one place to put it?

2022-11-01 04:47 UTC, xiaobill8 commented on docs/UserGuide.md
> +- in full
Don't see it though, I've placed it at the bottom with the Accepted Date Formats

2022-11-01 04:55 UTC, seetohjinwei approved these changes
LGTM!

2022-11-01 05:05 UTC, merged