User Guide: Elaborate on criteria for duplicate contacts/tasks
AY2223S1-CS2103T-T13-4/tp pull request #247
Opened 2022-10-31 13:03 UTC by bananamonkey4655

Fixes #203

2022-10-31 18:29 UTC, Nephelite requested changes

2022-10-31 18:29 UTC, Nephelite commented on docs/UserGuide.md
> +* For tasks: you cannot add another task of the same type with the **same person, assignment, description (and date if it is a `deadline` or `event`)** as an existing task.
Grammatical error. If you remove the brackets, you have 'the same person, assignment, description as an existing task'.

Also, should elaborate that all parameters must be the same for the task to count as a duplicate. As is right now, a layman could interpret this line as 'if any one of these are the same, the task will be a duplicate'.

2022-11-01 12:11 UTC, dexter-sim requested changes
Should also add a note in edit contact and edit task section of the features. That feature may also result in duplicate contact/task problem.

2022-11-02 04:48 UTC, Nephelite approved these changes

2022-11-02 04:57 UTC, dexter-sim approved these changes
lgtm

2022-11-02 04:57 UTC, merged