Add note for contact delete in user guide
AY2223S1-CS2103T-T13-4/tp pull request #249
Opened 2022-10-31 16:46 UTC by dexter-sim

2022-10-31 18:31 UTC, Nephelite requested changes

2022-10-31 18:31 UTC, Nephelite commented on docs/UserGuide.md
> +**:information_source: Notes about contact delete:**<br>
When you add notations like this, you should use a `<div>` border to make it stand out to the readers. Use the other instances of `<div>` usage in this UG as reference.

2022-11-01 02:12 UTC, dexter-sim commented on docs/UserGuide.md
> +**:information_source: Notes about contact delete:**<br>
Added div!

2022-11-02 04:49 UTC, Nephelite approved these changes

2022-11-03 05:17 UTC, merged